name: music_player_page_lego
description: "beautiful music player page lego"
#publish_to: 'none'
repository: https://github.com/flutter-lego/music_player_page_lego

version: 1.0.1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  june_flow_util: #@add
  styled_widget: #@add
  modal_bottom_sheet: #@add
  gap: #@add
  flutter_svg: #@add
  flutter_neumorphic_plus: #@add

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  assets:
    - assets/lego/music_player_page_lego/
  uses-material-design: true

topics:
  - lego